export { createTree, applyAction, tick, conditionModifier, MAX_DEPTH } from './tree.js';
export { SPECIES } from './species.js';
export { nextRand } from './rng.js';
export type { SpeciesParams } from './species.js';
export { BonsaiTree } from './BonsaiTree.js';
export { GrowthEngine } from './GrowthEngine.js';
export { CareLogReplay } from './CareLogReplay.js';
export { PruneEngine } from './PruneEngine.js';
export { WireEngine, WIRE_MAX_THICKNESS, WIRE_MAX_BEND_DEG } from './WireEngine.js';
export type { WireResult } from './WireEngine.js';
export { StatTerrain } from './StatTerrain.js';
export type { TerrainStat } from './StatTerrain.js';
export { StatDeriver } from './StatDeriver.js';
export type { VoxelSet, StructuralStats, TerrainBonuses } from './StatDeriver.js';
